apiVersion: apps/v1
kind: Deployment
metadata:
  name: person-counter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: person-counter
  template:
    metadata:
      labels:
        app: person-counter
    spec:
      containers:
      - name: person-counter
        image: moreillon/person-counter
        ports:
        - containerPort: 8051
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: person-counter
  name: person-counter
spec:
  ports:
  - port: 8051
    nodePort: 30051
  selector:
    app: person-counter
  type: LoadBalancer
