apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: object-detection
  template:
    metadata:
      labels:
        app: object-detection
    spec:
      containers:
      - name: object-detection
        image: 192.168.1.2:5000/object-detection
        ports:
        - containerPort: 8051
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: object-detection
  name: object-detection
spec:
  ports:
  - port: 8051
    nodePort: 30051
  selector:
    app: object-detection
  type: LoadBalancer
