apiVersion: apps/v1
kind: Deployment
metadata:
  name: person-counter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: person-counter
  template:
    metadata:
      labels:
        app: person-counter
    spec:
      containers:
      - name: person-counter
        image: moreillon/person-counter
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: person-counter
  name: person-counter
spec:
  ports:
  - port: 80
  selector:
    app: person-counter
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: person-counter
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - personcounter.maximemoreillon.com
    secretName: person-counter
  rules:
  - host: personcounter.maximemoreillon.com
    http:
      paths:
      - path: /
        backend:
          serviceName: person-counter
          servicePort: 80
